// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6WnTduCNkQZH6SBdBF7dB21kneCbUli0',
    appId: '1:446038377408:web:ce72e47b2a990911fa7e25',
    messagingSenderId: '446038377408',
    projectId: 'amgo-mango',
    authDomain: 'amgo-mango.firebaseapp.com',
    storageBucket: 'amgo-mango.firebasestorage.app',
    measurementId: 'G-61XTY18138',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB14CRyA-aqjP4giQeuVaNKORh5DE2cby4',
    appId: '1:446038377408:android:2ab675e98286bba6fa7e25',
    messagingSenderId: '446038377408',
    projectId: 'amgo-mango',
    storageBucket: 'amgo-mango.firebasestorage.app',
  );

}